# Docker Compose para el sistema completo
services:
  # Servicio OCR con Tesseract
  ocr-service:
    build:
      context: .
      dockerfile: Dockerfile.ocr
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Aplicación principal FastAPI
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images:ro
      - .:/app
    environment:
      - PYTHONPATH=/app
      - OCR_SERVICE_URL=http://ocr-service:8001
    depends_on:
      - ocr-service
    command: uv run fastapi dev main_ocr.py --host 0.0.0.0 --port 8000
